"""Sample opportunities seed + startup user seeding."""
import os
from datetime import datetime, timezone

from .db import db
from .security import hash_password

SAMPLE_OPPORTUNITIES = [
    {
        "id": "opp-blr-grade-a",
        "name": "Grade-A Office Park",
        "location": "Outer Ring Road, Bengaluru",
        "asset_type": "A-Grade Office",
        "tenant": "Global Technology Company",
        "image": "/generated/assets/opp-blr-grade-a.png",
        "image_fallback": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=85",
        "min_investment": 1000000,
        "asset_value_cr": 80,
        "target_irr": 16.0,
        "target_irr_range": "15-17%",
        "rental_yield": 8.5,
        "lease_term_years": 9,
        "occupancy": 100,
        "tenure_years": 6,
        "funded_pct": 64,
        "leverage_available": True,
        "risk_score": 78,
        "tags": ["Pre-Leased", "A-Grade", "Leverage Available"],
        "highlight": "Bengaluru's premier ORR corridor; pre-leased to a global technology company on a 9-year lock-in.",
    },
    {
        "id": "opp-pune-premium",
        "name": "Premium Commercial Asset",
        "location": "Kharadi, Pune",
        "asset_type": "Pre-Leased Office",
        "tenant": "Enterprise Occupier",
        "image": "/generated/assets/opp-pune-premium.png",
        "image_fallback": "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1200&q=85",
        "min_investment": 2000000,
        "asset_value_cr": 55,
        "target_irr": 15.0,
        "target_irr_range": "14-16%",
        "rental_yield": 8.2,
        "lease_term_years": 8,
        "occupancy": 100,
        "tenure_years": 6,
        "funded_pct": 48,
        "leverage_available": False,
        "risk_score": 76,
        "tags": ["Pre-Leased", "Enterprise Tenant"],
        "highlight": "Stable enterprise occupier with strong covenants. Leverage availability under review.",
    },
    {
        "id": "opp-hyd-tower",
        "name": "Commercial Office Tower",
        "location": "Hitec City, Hyderabad",
        "asset_type": "A-Grade Office",
        "tenant": "Listed Corporate",
        "image": "/generated/assets/opp-hyd-tower.png",
        "image_fallback": "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=85",
        "min_investment": 2500000,
        "asset_value_cr": 120,
        "target_irr": 16.0,
        "target_irr_range": "15-17%",
        "rental_yield": 9.0,
        "lease_term_years": 9,
        "occupancy": 98,
        "tenure_years": 6,
        "funded_pct": 38,
        "leverage_available": True,
        "risk_score": 82,
        "tags": ["A-Grade", "Listed Tenant", "Leverage Available"],
        "highlight": "Largest asset on the platform; pre-leased to a listed Indian corporate with CPI escalations.",
    },
    {
        "id": "opp-ncr-business-park",
        "name": "Pre-leased Business Park",
        "location": "Gurugram, NCR",
        "asset_type": "Grade-A Office",
        "tenant": "MNC Occupier",
        "image": "/generated/assets/opp-ncr-business-park.png",
        "image_fallback": "https://images.unsplash.com/photo-1549757521-4160565ff3de?w=1200&q=85",
        "min_investment": 1500000,
        "asset_value_cr": 95,
        "target_irr": 15.0,
        "target_irr_range": "14-16%",
        "rental_yield": 8.7,
        "lease_term_years": 8,
        "occupancy": 100,
        "tenure_years": 6,
        "funded_pct": 71,
        "leverage_available": True,
        "risk_score": 80,
        "tags": ["MNC Tenant", "NCR", "Leverage Available"],
        "highlight": "100% leased to an MNC occupier in India's largest office market by absorption.",
    },
    {
        "id": "opp-bkc-skyline",
        "name": "BKC Skyline Towers",
        "location": "Bandra-Kurla Complex, Mumbai",
        "asset_type": "A-Grade Office",
        "tenant": "Global Tech MNC",
        "image": "/generated/assets/opp-bkc-skyline.png",
        "image_fallback": "https://images.unsplash.com/photo-1600531529272-023c4b821f14?w=1200&q=85",
        "min_investment": 2500000,
        "asset_value_cr": 142,
        "target_irr": 14.6,
        "target_irr_range": "14-15%",
        "rental_yield": 8.4,
        "lease_term_years": 9,
        "occupancy": 100,
        "tenure_years": 6,
        "funded_pct": 84,
        "leverage_available": True,
        "risk_score": 88,
        "tags": ["Pre-Leased", "Marquee", "Mumbai CBD"],
        "highlight": "Trophy BKC asset with 9-year lock-in to a global tech MNC.",
    },
    {
        "id": "opp-chen-marina",
        "name": "Marina Tech Square",
        "location": "OMR, Chennai",
        "asset_type": "IT Park",
        "tenant": "Insurance Captive",
        "image": "/generated/assets/opp-chen-marina.png",
        "image_fallback": "https://images.unsplash.com/photo-1568992687947-868a62a9f521?w=1200&q=85",
        "min_investment": 800000,
        "asset_value_cr": 48,
        "target_irr": 15.8,
        "target_irr_range": "15-16%",
        "rental_yield": 9.0,
        "lease_term_years": 8,
        "occupancy": 94,
        "tenure_years": 6,
        "funded_pct": 33,
        "leverage_available": False,
        "risk_score": 72,
        "tags": ["Entry-Level", "Captive Tenant"],
        "highlight": "Lowest ticket size; ideal for first-time fractional investors.",
    },
    {
        "id": "opp-orr-prism",
        "name": "ORR Prism Business Park",
        "location": "Outer Ring Road, Bengaluru",
        "asset_type": "IT Park",
        "tenant": "Fortune 500 SaaS",
        "image": "/generated/assets/opp-orr-prism.png",
        "image_fallback": "https://images.unsplash.com/photo-1576731753569-3e93a228048c?w=1200&q=85",
        "min_investment": 1500000,
        "asset_value_cr": 88,
        "target_irr": 16.2,
        "target_irr_range": "15-17%",
        "rental_yield": 9.1,
        "lease_term_years": 7,
        "occupancy": 96,
        "tenure_years": 6,
        "funded_pct": 64,
        "leverage_available": True,
        "risk_score": 83,
        "tags": ["IT Park", "Anchor Tenant", "Leverage Available"],
        "highlight": "Bengaluru's tech corridor with 96% occupancy and CPI-linked rent escalations.",
    },
    {
        "id": "opp-leverage-alpha",
        "name": "Alpha Leverage Pool I",
        "location": "Pan-India Diversified",
        "asset_type": "Leveraged Fractional",
        "tenant": "Multiple Marquee Tenants",
        "image": "/generated/assets/opp-leverage-alpha.png",
        "image_fallback": "https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=1200&q=85",
        "min_investment": 2000000,
        "asset_value_cr": 250,
        "target_irr": 17.0,
        "target_irr_range": "16-17%",
        "rental_yield": 8.8,
        "lease_term_years": 8,
        "occupancy": 99,
        "tenure_years": 6,
        "funded_pct": 18,
        "leverage_available": True,
        "risk_score": 79,
        "tags": ["Leverage Product", "Coming Soon", "Diversified"],
        "highlight": "Property Verse's flagship leverage-backed pool — up to 17% projected IRR through structured leverage.",
    },
]


async def seed_database():
    """Seed indexes + admin + demo investor on app startup."""
    await db.users.create_index("email", unique=True)
    await db.login_attempts.create_index("identifier")

    admin_email = os.environ.get("ADMIN_EMAIL", "admin@propertyverse.in").lower()
    admin_password = os.environ.get("ADMIN_PASSWORD", "admin123")
    if not await db.users.find_one({"email": admin_email}):
        await db.users.insert_one({
            "email": admin_email,
            "password_hash": hash_password(admin_password),
            "name": "Property Verse Admin",
            "role": "admin",
            "created_at": datetime.now(timezone.utc).isoformat(),
            "watchlist": [],
        })

    test_email = os.environ.get("TEST_USER_EMAIL", "investor@propertyverse.in").lower()
    test_password = os.environ.get("TEST_USER_PASSWORD", "Investor2025!")
    existing = await db.users.find_one({"email": test_email})
    if not existing:
        await db.users.insert_one({
            "email": test_email,
            "password_hash": hash_password(test_password),
            "name": "Demo Investor",
            "role": "investor",
            "created_at": datetime.now(timezone.utc).isoformat(),
            "watchlist": ["opp-blr-grade-a", "opp-leverage-alpha"],
        })
    else:
        await db.users.update_one(
            {"_id": existing["_id"]},
            {"$set": {"watchlist": ["opp-blr-grade-a", "opp-leverage-alpha"]}},
        )
